### ISSUE TITLE
skidded 

### ISSUE THREAD

**Issue by PrototypeHub** [dorukqpx/suntai#1]
the issue is that it's skidded :(

**Comment by dorukqpx** [comment]
> the issue is that it's skidded skidded :(
The nameless guy's crying issue :(
So sad

**Comment by PrototypeHub** [comment]
> > the issue is that it's skidded skidded :(
> > The nameless guy's crying issue :(
> > So sad

MY NIGGA CODING A KILL AURA AND SHIT IS FUCKING EASY INSTEAD OF SKIDDING VAMPS SYTRONIGHT SCRIPT

**Comment by dorukqpx** [comment]
> > > the issue is that it's skidded skidded :(
> > > The nameless guy's crying issue :(
> > > So sad
> 
> MY NIGGA CODING A KILL AURA AND SHIT IS FUCKING EASY INSTEAD OF SKIDDING VAMPS SYTRONIGHT SCRIPT

Vamp skids rektsky's killaura i can report you

**Comment by dorukqpx** [comment]
> > > the issue is that it's skidded skidded :(
> > > The nameless guy's crying issue :(
> > > So sad
> 
> MY NIGGA CODING A KILL AURA AND SHIT IS FUCKING EASY INSTEAD OF SKIDDING VAMPS SYTRONIGHT SCRIPT

No n-word in github

**Comment by SusanYT00** [comment]
Maybe sytro skidded who knows now dont ask if we skidded look at the message and you'll understand join our discord i will tell u complete story and btw sempiller is my friend he didnt skid and he helped me too

**Comment by dorukqpx** [comment]
> Maybe sytro skidded who knows now dont ask if we skidded look at the message and you'll understand join our discord i will tell u complete story and btw sempiller is my friend he didnt skid and he helped me too

If sempiller is your friend WHO ARE YOU
